### ISSUE TITLE
Can't Save Wallpaper when special characters are used in Thread name

### ISSUE THREAD

**Issue by radishism** [Rawns/Reddit-Wallpaper-Changer#41] opened 2017-02-28 10:44 UTC
Throws "Unable to save wallpaper locally" error on thread with ? character. e.g. https://www.reddit.com/r/EarthPorn/comments/5v92tl/mckinley_denali_whatever_you_wanna_call_it_its/

**Comment by Rawns** [comment] 2017-03-02 21:56
Can you confirm your version? This was fixed under a previous release: https://github.com/Rawns/Reddit-Wallpaper-Changer/issues/22

**Comment by radishism** [comment] 2017-03-03 14:03
Hi,

I'm running 1.0.12.0 - Just done it again with a path including ?

Cheers

Ian

**Comment by padrino257** [comment] 2017-03-03 14:55
Interesting. I will have a look at this later tonight, maybe question marks are not returned by the method I used for getting invalid characters.
@radishism could you also post your log to pastebin so I can see which threads are triggering the error messages?

**Comment by radishism** [comment] 2017-03-03 15:20
Hi,

Not sure about pastbin, but hopefully this will work. The best example is:

28/02/2017 10:34:55 - LTP-IANS-01: Found a wallpaper! Title: McKinley? Denali? Whatever you wanna call it, it's HUGE.
[RWC.log.txt](https://github.com/Rawns/Reddit-Wallpaper-Changer/files/817117/RWC.log.txt)

**Comment by padrino257** [comment] 2017-03-03 15:21
That'll do, thanks!

**Comment by padrino257** [comment] 2017-03-03 16:44
This is odd, I cannot reproduce the behavior with the exact thread titles that are leading to problems on your machine. 
What operating system are you using?

**Comment by Rawns** [comment] 2017-03-06 15:15
I've found the problem. Removing the illegal characters from the post title has only been built into the "auto-save wallpapers" function, and your log shows you have auto-save disabled so presume you are manually saving select wallpapers like the one mentioned above from the right click option? 

The manual save function does not have the check for illegal characters. I've updated the code to include this so it will be included in the next release.

**Comment by Rawns** [comment] 2017-03-06 15:28
Fix pushed to dev branch. Will close once live.

**Comment by radishism** [comment] 2017-03-07 09:37
I am manually saving. Well found! 

Thanks for your efforts and thanks for a great product guys.

**Comment by Rawns** [comment] 2017-03-27 18:55
Fixed in 1.0.13.0

**Closed by Rawns** 2017-03-27 18:55 UTC
Labels: Fixed, Pending Closure
