### ISSUE TITLE
"Your query is bringing up no results" when using Truly Random setting

### ISSUE THREAD

**Issue by BlackDragon17** [Rawns/Reddit-Wallpaper-Changer#23] opened 2017-02-12 02:46 UTC
I'm running Reddit Wallpaper Changer 1.0.9.0 on Windows 10 with the "Truly Random" setting in the "Grab Wallpaper By" field, and the following list of subreddits as source:

AerialPorn+auroraporn+AutumnPorn+bridgeporn+CabinPorn+carporn+CloudPorn+CLOUDS+EarthPorn+ExposurePorn+HI_Res+iceporn+ImaginaryDwellings+ImaginaryForests+ImaginaryLakes+ImaginaryMountains+ImaginaryRivers+ImaginarySkyscapes+ImaginaryStarscapes+ImaginaryStarships+ImaginaryWaterfalls+ImaginaryWeather+ImaginaryWorlds+lakeporn+LandscapeAstro+Mountainpics+natureporn+RoadPorn+schweiz+seaporn+SilhouettePorn+SkyPorn+spaceporn+SpringPorn+StarshipPorn+SummerPorn+SunriseSunset+sunset+waterporn+WeatherPorn+winterporn

About 60% of the time when I tell RWC to change wallpaper, it will jump to one of the subreddits, find nothing (even though I do not have a search query due to the truly random setting), jump to another subreddit, find nothing there either, and then simply give up and display "Your query is bringing up no results".

Every single one of the subreddits I use as source is full of image posts, and I do not have anything blacklisted.

Below is what RWC writes to it's logfile when the described issue occurs:

12.02.2017 03:33:18 - DRAGON: Changing wallpaper.
12.02.2017 03:33:19 - DRAGON: The background worker started successfully and is looking for a wallpaper.
12.02.2017 03:33:19 - DRAGON: Sellected sub to search: SunriseSunset
12.02.2017 03:33:19 - DRAGON: Full URL Search String: http://www.reddit.com/r/SunriseSunset/random.json?p=d0c15c4a-7e00-4d34-b218-fedbb7a9223c
12.02.2017 03:33:19 - DRAGON: Searching Reddit for a wallpaper.
12.02.2017 03:33:23 - DRAGON: Found a wallpaper! Title: What A Show - Act 2, URL: https://youtu.be/zuKRfeQvlOk, ThreadID: 4d60je
12.02.2017 03:33:23 - DRAGON: Not a direct wallpaper URL, searching again.
12.02.2017 03:33:23 - DRAGON: Changing wallpaper.
12.02.2017 03:33:23 - DRAGON: The background worker started successfully and is looking for a wallpaper.
12.02.2017 03:33:23 - DRAGON: Sellected sub to search: ImaginaryLakes
12.02.2017 03:33:23 - DRAGON: Full URL Search String: http://www.reddit.com/r/ImaginaryLakes/random.json?p=b61166d0-c71e-4af6-950e-06096ce40e08
12.02.2017 03:33:23 - DRAGON: Searching Reddit for a wallpaper.
12.02.2017 03:33:26 - DRAGON: Found a wallpaper! Title: Ming-Men Lake by Sean Soong, URL: http://seansoong.deviantart.com/art/Ming-Men-Lake-358359052, ThreadID: 2ov79j
12.02.2017 03:34:56 - DRAGON: No results from the search query.

**Comment by BlackDragon17** [comment] 2017-02-12 03:01
I think two possible solutions to this behavior could be:

1. Making RWC capable of interpreting DeviantArt links, as in, when it receives an indirect DA image link ([example](http://seansoong.deviantart.com/art/Ming-Men-Lake-358359052)), it should convert it to a direct image link ([example](http://orig01.deviantart.net/792c/f/2013/067/7/7/ming_men_lake_by_seansoong-d5xcvm4.jpg)).

2. Increasing the number of times that RWC tries to change the wallpaper before giving up from 2 to, for example, 5.

**Comment by padrino257** [comment] 2017-02-12 07:42
> Making RWC capable of interpreting DeviantArt links, as in, when it receives an indirect DA image link (example), it should convert it to a direct image link (example). 

A logic for that is in place using oembed. The URL for your image is turned into: http://backend.deviantart.com/oembed?url=http://seansoong.deviantart.com/art/Ming-Men-Lake-358359052 and from the result of that request the direct link may be received.

> Increasing the number of times that RWC tries to change the wallpaper before giving up from 2 to, for example, 5.

It sits at 50, however I think not every unsuccessful search will start a new one, especially when there is a bug.

@Rawns: To me, it seems as if the HttpWebRequest to check for an image you inserted at the very beginning of setWallpaper causes the issue observed here. For deviantart URLs I get a timeout every time which throws the exception that leads to the logmessages observed by @BlackDragon17. Adding `if (!url.Contains("deviantart"))` around that bit of code allows RWC to set the wallpaper in question here. 
Maybe the check for deleted images and direct image links should be integrated into the work of the backgroundworker as it seems quite specific to the site that the program is pulling from?

**Comment by Rawns** [comment] 2017-02-12 09:56
Thanks for the info. I'll get this fixed in the next release. :)

**Comment by padrino257** [comment] 2017-02-12 23:40
Theoretically, RWC should start looking for another Wallpaper in a situation as described by @BlackDragon17, right?
As far as I can tell, the intended behavior is Timer breakBetweenChange is started, ticks after a second and essentially restarts the wallpaper search (by restarting the changeWallpaperTimer again).

After playing around with it for a while though, I am a little confused though. 

Are you sure that restarting a Timer from BackgroundWorker works? As far as I can tell, the Timer never ticks. 

Replacing 
`breakBetweenChange.Enabled = true;`
by
`this.Invoke((MethodInvoker)(() => {breakBetweenChange.Enabled = true;}));`
works. (Source: http://stackoverflow.com/questions/9940293/enable-system-form-timer-from-backgroundworker)

I doubt that this is best practice though and maybe it will cause other bugs. Timers.Timer is mentioned frequently as an alternative to Windows.Forms.Timer for multithreaded applications, but I haven't had the time to look into what makes that better and how to get it to work in RWC.

**Comment by padrino257** [comment] 2017-02-16 11:15
Added pull request #27 to fix RWC entering a state where it is running but no timers to search for a wallpaper are enabled, as described in my last comment.

**Comment by Rawns** [comment] 2017-02-17 11:01
Committed the changes. :) 

I've also moved the "is an image URL?" and "is still on Imgur?" checks into the background worker process when actually looking for a wallpaper, rather than at the 'changing' stage. I've been running a new build in a VM with my changes, your commit and @BlackDragon17 's settings and set it to change my wallpaper every minute.  It's been rnning for about an hour now and it seems to be running quite happily. It's also pulled a few links form DeviantArt too without any problems. :)

**Comment by Rawns** [comment] 2017-02-17 11:06
Pending closure, changes to be included in 1.0.10.

**Comment by Rawns** [comment] 2017-02-18 22:36
Fixed.

**Closed by Rawns** 2017-02-18 22:36 UTC
Labels: Fixed, Pending Closure
